language: php

dist: xenial

php:
  - 5.6
  - 7.4

before_script:
    - sudo apt-get install parallel
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || true
    - composer install --dev --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - ls -d tests/Composer/Test/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/complete.phpunit.xml {};' || exit 1
